---
title: "Estadística I"
---
<br>
<p>
Profesor: Víctor Macías E.
<br>
E-mail: victor.macias@mail.udp.cl
</p>
<br>

<h2>Descripción del curso</h2>

La asignatura Estadística I es el primer curso estadístico de la carrera de Ingeniería Comercial y entrega las herramientas necesarias para realizar análisis descriptivos de datos, incluyendo formas simples de modelar relaciones entre variables, con la intención de facilitar e iluminar la toma de decisiones económicas o de negocios. Al mismo tiempo, entrega los fundamentos básicos de la teoría de probabilidades para la modelación de fenómenos con base probabilística. Se espera que los estudiantes sean capaces de sistematizar datos obtenidos de la realidad circundante y elaborar hipótesis que expliquen el comportamiento de dicha realidad.


<h2>Objetivos del aprendizaje</h2>

<ul>
  <li>Utilizar técnicas básicas de la estadística descriptiva y establecer relaciones empíricas entre variables que aporten a la toma de decisiones.</li>
  <li>Realizar análisis en forma reproducible y letrada (literate), es decir, que sean transparentes para un tercero y que, tanto la documentación, el medio elegido (por ejemplo, el software) como la organización del análisis haga factible y fácil reproducir el mismo análisis del autor.</li>
</ul>

Este curso aporta al perfil de egreso del estudiante en los siguientes aspectos:

<ul>
  <li>Desarrollo de competencias analíticas y de resolución de problemas.</li>
  <li>Desarrollar competencias tecnológicas: programación, ciencia de datos, TI.</li>
</ul>

<h2>Programa del curso <a href= "ProgramaCurso/Programa Estadistica I (syllabus 2021-1).pdf">[link]</a></h2>

El curso está estructurado en 4 unidades:

<ol>
    <li>Estadística descriptiva y visualización estadística</li>
    <li>Modelación de datos con regresión lineal</li>
    <li>Variables aleatorias y probabilidad</li>
    <li>Estadísticas muestrales como variables aleatorias</li>
</ol>

<h2>Evaluaciones</h2>

<ul>
    <li>Controles individuales (10%)</li>
    <li>Prueba solemne individual (20%)</li>
    <li>Participación en clases (20%)</li>
    <li>Trabajo semestral (50%)</li>
</ul>



